apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: poring86/gitopsfc
  newTag: edb87c28a39fa537bff6e2d87035be8cf0051346
